resources:
  - name: Aql_ART_2
    type: Aql
    configuration:
      sourceArtifactory: zenArt
      query: items.find({"@build.name":{"$eq":"art"}})
      addedProperties:
        key1: value1
        key2: value2
      mappings:
        - name: mapping1
          input: IN
          output: test1
        - name: mapping2
          input: IN
          output: test2

pipelines:
  - name: pipelines_ART_BASH_2
    configuration:
      environmentVariables:
        readOnly:
          my_env_var: "hello"
    steps:
      - name: step_1
        type: Bash
        configuration:
          inputResources:
            - name: Aql_ART_2 
              trigger: true
          outputResources:
            - name: myBuildInfo       
        execution:
          onExecute:
            - echo $my_env_var
            - if [ -z $app_version ]; then add_pipeline_variables app_version=1.0.0; else app_version=$(bump_semver $app_version minor); fi
            - write_output myBuildInfo "buildNumber=$app_version"
            - add_run_variables run_var="hello"
