resources:
  - name: Aql_ART_1
    type: Aql
    configuration:
      sourceArtifactory: zenArt
      query: items.find({"@build.name":{"$eq":"art"}})
      addedProperties:
        key1: value1
        key2: value2
      mappings:
        - name: mapping1
          input: IN
          output: test1
        - name: mapping2
          input: IN
          output: test2

pipelines:
  - name: pipelines_ART_1
    configuration:
      environmentVariables:
        readOnly:
          my_env_var: "hello"
    steps:
      - name: step_1
        type: Bash
        configuration:
          inputResources:
            - name: Aql_ART_1  
              trigger: true            
        execution:
          onExecute:
            - echo $my_env_var
