resources:
  - name: myBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: zenArt

pipelines:
  - name: createReleaseBundlePipeline
    steps:
      - name: createReleaseBundleStep
        type: CreateReleaseBundle
        configuration:
          releaseBundleName: my
          releaseBundleVersion: "${run_number}"
          dryRun: true
          inputResources:
            - name: myBuildInfo
          outputResources:
            - name: my
