resources:
  - name: FileSpec_0007
    type: FileSpec
    configuration:
      sourceArtifactory: zenArt
      pattern: "test-local/setup/"
      recursive: false
      offset: 1@3

pipelines:
  - name: pipelines_FLSPEC_0007
    steps:
      - name: step_FLSPEC_0007
        type: Bash
        configuration:
          inputResources:
            - name: FileSpec_0007 
              trigger: true
        execution:
          onExecute:
            - write-output "executing step..."
