resources:
  - name: FileSpec_1
    type: FileSpec
    configuration:
      sourceArtifactory: zenArt
      pattern: "test-local/setup/"
      recursive: false
      offset: 1@3
 
pipelines:
  - name: pipelines_FLSPEC_0014
    steps:
      - name: step_FLSPEC_0014
        type: PowerShell
        configuration:
          nodePool: win_2019
          inputResources:
            - name: FileSpec_1
        execution:
          onExecute:
            - write-output "executing step..."
